### ISSUE TITLE
Proyecto Final

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/proyecto-pulsador-equipo-julio-cesar-gonzalez-lopez#1]
[ProyectoFinal.zip](https://github.com/SistemasTecTlaxiaco/proyecto-pulsador-equipo-julio-cesar-gonzalez-lopez/files/7818803/ProyectoFinal.zip)

https://user-images.githubusercontent.com/90294297/148314483-74b35aca-eb45-4853-84ba-adb81493ae7d.mp4

**Comment by josealfredo79** [comment]
Bien hecho y revisado
